keys:
  - &user_olivertosky 656968EFE265ED715AF5F2BF1CDC6147DE47244F
  - &host_ot-desktop age15axcretngjgf0exjf7fnfx4pwmak9lwm0y6qdl5h4wxhyfgdzfxsazrn7u
  # - &host_ot-desktop age1q3h69aqzf3rxwckw8yw25z8rks9j3rgm0vsghqku2dgfz8n2wyysvfdrze


creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - pgp:
        - *user_olivertosky
      age:
        - *host_ot-desktop
